version: '2.0'
services:
  web:
    image: docker.pkg.github.com/propulsioncarriere/propulsetacarriere/nginx:latest
    ports:
    - "8080:80"
    depends_on:
    - app
  app:
    image: docker.pkg.github.com/propulsioncarriere/propulsetacarriere/app:latest
    depends_on:
    - database
    volumes:
    - ".env:/var/www/.env"
  database:
    image: mysql:5.6
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_USER=${DB_USERNAME}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_RANDOM_ROOT_PASSWORD=TRUE"
volumes:
  dbdata: